model_dir : 'D:/save_res/'
test_img_path : 'D:/IC15/test_img/'
submit_path : 'D:/EAST-Remade/pipeline/evaluate/submit'
train_img_path : 'D:/IC15/train_img/'
train_gt_path  : 'D:/IC15/train_gt/'
save_path      : 'D:/save_res'
model_name : 'ResNet'
evaluate_path : 'D:/EAST-Remade/pipeline/evaluate'
parent_path : 'D:/EAST-Remade/pipeline/evaluate'
batch_size     : 11
lr             : 0.001
num_workers    : 4
epoch_iter     : 51
save_interval  : 5 